### ISSUE TITLE
代码块内不要增加格式

### ISSUE THREAD

**Issue by wxy** [LCTT/LCTT-Helper#24]
个别情况下，网页的代码块会存在黑体和斜体或者链接这种情况，但是用\```CODE\```这种就要将内部 CODE 完全当成代码，不支持 MD 的。此外 \`\` 这种也是。

**Comment by wxy** [comment]
比如这篇 http://www.brendangregg.com/blog/2016-10-27/dtrace-for-linux-2016.html

**Comment by StdioA** [comment]
Fixed.
