### ISSUE TITLE
代码不能处理

### ISSUE THREAD

**Issue by oska874** [LCTT/LCTT-Helper#4]
没有吧代码翻译成标准格式，

比如：

$ git init --bare --shared /opt/jupiter.git

应该处理成：

```
  $ git init --bare --shared /opt/jupiter.git
```

但是实际上只是当普通文本处理了。

ps: 这个是不是不好处理？

pss: 比如这篇 https://opensource.com/life/16/7/creating-your-first-git-repository ，工具生成的md 是这样的：

![image](https://cloud.githubusercontent.com/assets/4536559/18654838/c47b68de-7f16-11e6-8e4f-4658d946a3c2.png)

**Comment by bestony** [comment]
OK,以后贴链接，我直接去测试。
