### ISSUE TITLE
问题 html 粘贴有问题

### ISSUE THREAD

**Issue by oska874** [LCTT/LCTT-Helper#5]
这个 ： https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/?utm_source=javascriptweekly&utm_medium=email

将html粘贴过来以后有问题

原文：
![image](https://cloud.githubusercontent.com/assets/4536559/18655053/3792bfc4-7f18-11e6-94ff-b71066bba733.png)

粘贴后：

![image](https://cloud.githubusercontent.com/assets/4536559/18655056/416b5baa-7f18-11e6-85df-64996148c139.png)

生成md：

![image](https://cloud.githubusercontent.com/assets/4536559/18655062/4b69b408-7f18-11e6-9c6e-5609872cda88.png)

**Comment by bestony** [comment]
复制HTML后，进行一级处理，去掉多余的标签和样式。

**Comment by bestony** [comment]
看了下，这个是因为页面本身具备的syntaxhighlighter 高亮导致代码被table包围。
目前来说， 没办法进行自动处理。建议在碰见出现这样的问题的文章时，利用左侧的编辑器进行修改。修改后再进行转换。
