### ISSUE TITLE
处理有问题的网址

### ISSUE THREAD

**Issue by oska874** [LCTT/LCTT-Helper#6]
有些问题不好描述，我就把网址列出来，你试试看：

https://www.howtoforge.com/tutorial/octave-audio-signal-processing-ubuntu/

（列表我继续补充）

**Comment by bestony** [comment]
好的~以后有问题的链接都补充到这里吧。我每个都测试下。

**Comment by bestony** [comment]
https://www.howtoforge.com/tutorial/octave-audio-signal-processing-ubuntu/
这个页面中的大量代码、特殊方程都是不是利用特定的标签来处理的，比如code,而是使用的p.command这样的一个类来加入的，故而无法识别。建议配合编辑器本身的按钮编辑后再转换。

**Comment by oska874** [comment]
https://fedoramagazine.org/rust-meets-fedora/

连续两个代码区的  ```  会连续

**Comment by oska874** [comment]
http://phoronix.com/scan.php?page=news_item&px=ELC2016-Software-Updates

粘贴过来后格式乱了

chrome

**Comment by bestony** [comment]
@oska874  phoronix的文章我看了下，问题出在他的页面中没有P标签，是直接在DIV中放了TEXT的

**Comment by oska874** [comment]
http://www.tecmint.com/find-linux-kernel-version-distribution-name-version-number/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+tecmint+%28Tecmint%3A+Linux+Howto%27s+Guide%29

这个网站的，复制过来，图全部挂了

**Comment by keven2116** [comment]
图挂了应该是图片链接的问题，有墙啊；

**Comment by oska874** [comment]
但是复制到word就没问题啊，图挂指的是粘贴框里就没有图片的东西。

**Comment by oska874** [comment]
https://gorillalogic.com/blog/getting-started-with-ansible/?utm_source=webopsweekly&utm_medium=email
这个网页的内容不能一次复制粘提，而且粘贴时内容有丢失

**Comment by oska874** [comment]
https://www.smashingmagazine.com/2016/10/how-to-develop-a-chat-bot-with-node-js/?utm_source=nodeweekly&utm_medium=email
问题同上，复制过来丢内容

**Comment by bestony** [comment]
https://gorillalogic.com/blog/getting-started-with-ansible/?utm_source=webopsweekly&utm_medium=email 这个拖动处理后已经非常不错了。我测试了下。

**Comment by oska874** [comment]
http://www.linuxandubuntu.com/home/how-to-setup-a-wifi-in-arch-linux-using-terminal

生成的md问题多

**Comment by oska874** [comment]
https://www.ostechnix.com/download-rpm-package-dependencies-centos/

复制粘贴丢内容、丢图

**Comment by bestony** [comment]
这两天家里断网了，恢复后处理。

**Comment by oska874** [comment]
http://www.tecmint.com/install-configure-ganglia-monitoring-centos-linux/

里面的多级列表序号有问题

**Comment by oska874** [comment]
http://www.tecmint.com/check-linux-hard-disk-bad-sectors-bad-blocks/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+tecmint+%28Tecmint%3A+Linux+Howto%27s+Guide%29

问题：会生成这样的代码：

```
```

$ sudo badblocks -v /dev/sda10 > badsectors.txt

```[![Scan Hard Disk Bad Sectors in Linux](http://www.tecmint.com/wp-content/uploads/2016/10/Scan-Hard-Disk-Bad-Sectors-in-Linux.png)][3]

```

结果图片就不能正常显示了
```

**Comment by oska874** [comment]
http://firstround.com/review/forget-technical-debt-heres-how-to-build-technical-wealth/

处理错误

**Comment by bestony** [comment]
www.tecmint.com 的代码错误问题已修复

**Comment by oska874** [comment]
http://www.linuxandubuntu.com/home/how-to-install-linux-mint-from-usb

多级列表

**Comment by wxy** [comment]
@bestony 看来你得多找两个人来帮你，issue 太多了，哈哈哈

**Comment by StdioA** [comment]
我前端写的不好，等我有时间研究一下这个，看看我能不能帮上忙

**Comment by oska874** [comment]
http://www.webupd8.org/2016/11/xfce-gets-do-not-disturb-mode-and-per.html

**Comment by oska874** [comment]
http://www.linuxandubuntu.com/home/how-to-use-vi-editor

**Comment by oska874** [comment]
https://www.gamingonlinux.com/articles/user-editorial-steam-machines-steamos-after-a-year-in-the-wild.8474

**Comment by StdioA** [comment]
@oska874 以后请把有问题的网址放在[这里](https://github.com/LCTT/LCTT-Helper/projects/2) 以便于追踪。  
一个 issue 里放这么多问题有点让人头大:new_moon_with_face:  
之前的错误网址我稍后会整理。
